//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sevenimport
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public empresa()
        {
            this.marcas = new HashSet<marca>();
            this.services = new HashSet<service>();
            this.partners = new HashSet<partner>();
            this.quienes = new HashSet<quiene>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Logo { get; set; }
    
        public virtual ICollection<marca> marcas { get; set; }
        public virtual ICollection<service> services { get; set; }
        public virtual ICollection<partner> partners { get; set; }
        public virtual ICollection<quiene> quienes { get; set; }
    }
}
