//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sevenimport
{
    using System;
    using System.Collections.Generic;
    
    public partial class marca
    {
        public marca()
        {
            this.products = new HashSet<product>();
            this.contacts = new HashSet<contact>();
            this.socials = new HashSet<social>();
            this.sliders = new HashSet<slider>();
            this.imageMarcas = new HashSet<imageMarca>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Logo { get; set; }
        public int IdEmpresa { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<contact> contacts { get; set; }
        public virtual ICollection<social> socials { get; set; }
        public virtual ICollection<slider> sliders { get; set; }
        public virtual ICollection<imageMarca> imageMarcas { get; set; }
    }
}
