//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sevenimport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class importEntities : DbContext
    {
        public importEntities()
            : base("name=importEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<empresa> empresas { get; set; }
        public virtual DbSet<marca> marcas { get; set; }
        public virtual DbSet<partner> partners { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<social> socials { get; set; }
        public virtual DbSet<quiene> quienes { get; set; }
        public virtual DbSet<slider> sliders { get; set; }
        public virtual DbSet<imageMarca> imageMarcas { get; set; }

        public System.Data.Entity.DbSet<sevenimport.Models.ItemModel> ItemModels { get; set; }
    }
}
